### ISSUE TITLE
blank page after running npm dev

### ISSUE THREAD

**Issue by ryhnatwoods** [FairyEver/demo-require-context#1]
![image](https://user-images.githubusercontent.com/6201481/40881538-928bae78-66fb-11e8-8938-c6893725d6b7.png)
![image](https://user-images.githubusercontent.com/6201481/40881548-b5b65420-66fb-11e8-8896-0749af2f95d0.png)

**Comment by FairyEver** [comment]
The problem is because of my negligence, I ignored the file path difference between the UNIX system and the Windows system, which led me to only consider the '/' separator of the Unix system when I split the path, and now I modified the code, and the program should run normally on the Windows, but I have no test, because I do not have a Windows environment, please Let me know after the test. Thank you.

**Comment by FairyEver** [comment]
https://github.com/FairyEver/demo-require-context/blob/813e436c6045d46e6744d88173bcfd7f1b38f109/src/router/req.js#L5-L14
